name: Test
on: [pull_request]
jobs:
  build:
    name: run browser tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v4
      - name: setup JVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }} # This actually isn't set, but it's not complaining atm.
          native-image-job-reports: 'true'
      - name: setup-browser
        uses: browser-actions/setup-firefox@v1
      - name: call gradle to run test
        run: |
          sudo apt-get install tesseract-ocr
          /usr/bin/tesseract --version
          sudo apt-get install xvfb
          export DISPLAY=':99.0'
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          ./gradlew clean test